{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "20614724-490d-4cd8-b958-847f2e07ff23",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🚀 CREATING COMPREHENSIVE ALL INDIA DATASET...\n",
      "=================================================================\n",
      "📊 Original data loaded: 5768 records\n",
      "✅ Enhanced All India data saved: data/pollution_data_all_india_enhanced.csv\n",
      "🏙️ Total cities covered: 60\n",
      "🗺️ Total zones covered: 6\n",
      "📡 Total sensors: 128\n",
      "📊 Total records: 25,928\n",
      "\n",
      "📈 City Distribution:\n",
      "  Delhi: 1057 records\n",
      "  Jaipur: 1057 records\n",
      "  Lucknow: 1057 records\n",
      "  Kanpur: 1057 records\n",
      "  Chandigarh: 1057 records\n",
      "  Amritsar: 1057 records\n",
      "  Dehradun: 1057 records\n",
      "  Bangalore: 1057 records\n",
      "  Ludhiana: 336 records\n",
      "  Jalandhar: 336 records\n",
      "  Haridwar: 336 records\n",
      "  Chennai: 336 records\n",
      "  Hyderabad: 336 records\n",
      "  Visakhapatnam: 336 records\n",
      "  Coimbatore: 336 records\n",
      "\n",
      "🌍 Zone Distribution:\n",
      "  North: 8407 records\n",
      "  South: 4081 records\n",
      "  West: 3360 records\n",
      "  East: 3360 records\n",
      "  Central: 3360 records\n",
      "  North-East: 3360 records\n",
      "\n",
      "🎉 SUCCESS! Enhanced dataset created:\n",
      "   ✅ 60 Indian cities\n",
      "   ✅ 6 geographical zones\n",
      "   ✅ 128 total sensors\n",
      "   ✅ 25,928 total records\n",
      "   ✅ Realistic pollution patterns for each city\n",
      "\n",
      "📁 Output file: data/pollution_data_all_india_enhanced.csv\n"
     ]
    }
   ],
   "source": [
    "# add_all_india_cities_enhanced.py\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "def create_comprehensive_all_india_data():\n",
    "    \"\"\"Create comprehensive All India dataset with virtual sensors for all cities\"\"\"\n",
    "    \n",
    "    # Comprehensive list of 50+ major Indian cities with coordinates\n",
    "    INDIAN_CITIES = {\n",
    "        # Northern Cities\n",
    "        'Delhi': {'lat': 28.6139, 'lon': 77.2090, 'zone': 'North'},\n",
    "        'Jaipur': {'lat': 26.9124, 'lon': 75.7873, 'zone': 'North'},\n",
    "        'Lucknow': {'lat': 26.8467, 'lon': 80.9462, 'zone': 'North'},\n",
    "        'Kanpur': {'lat': 26.4499, 'lon': 80.3319, 'zone': 'North'},\n",
    "        'Ludhiana': {'lat': 30.9010, 'lon': 75.8573, 'zone': 'North'},\n",
    "        'Chandigarh': {'lat': 30.7333, 'lon': 76.7794, 'zone': 'North'},\n",
    "        'Amritsar': {'lat': 31.6340, 'lon': 74.8723, 'zone': 'North'},\n",
    "        'Jalandhar': {'lat': 31.3260, 'lon': 75.5762, 'zone': 'North'},\n",
    "        'Dehradun': {'lat': 30.3165, 'lon': 78.0322, 'zone': 'North'},\n",
    "        'Haridwar': {'lat': 29.9457, 'lon': 78.1642, 'zone': 'North'},\n",
    "        \n",
    "        # Southern Cities\n",
    "        'Bangalore': {'lat': 12.9716, 'lon': 77.5946, 'zone': 'South'},\n",
    "        'Chennai': {'lat': 13.0827, 'lon': 80.2707, 'zone': 'South'},\n",
    "        'Hyderabad': {'lat': 17.3850, 'lon': 78.4867, 'zone': 'South'},\n",
    "        'Visakhapatnam': {'lat': 17.6868, 'lon': 83.2185, 'zone': 'South'},\n",
    "        'Coimbatore': {'lat': 11.0168, 'lon': 76.9558, 'zone': 'South'},\n",
    "        'Kochi': {'lat': 9.9312, 'lon': 76.2673, 'zone': 'South'},\n",
    "        'Mysore': {'lat': 12.2958, 'lon': 76.6394, 'zone': 'South'},\n",
    "        'Madurai': {'lat': 9.9252, 'lon': 78.1198, 'zone': 'South'},\n",
    "        'Thiruvananthapuram': {'lat': 8.5241, 'lon': 76.9366, 'zone': 'South'},\n",
    "        'Mangalore': {'lat': 12.9141, 'lon': 74.8560, 'zone': 'South'},\n",
    "        \n",
    "        # Western Cities\n",
    "        'Mumbai': {'lat': 19.0760, 'lon': 72.8777, 'zone': 'West'},\n",
    "        'Pune': {'lat': 18.5204, 'lon': 73.8567, 'zone': 'West'},\n",
    "        'Ahmedabad': {'lat': 23.0225, 'lon': 72.5714, 'zone': 'West'},\n",
    "        'Nagpur': {'lat': 21.1458, 'lon': 79.0882, 'zone': 'West'},\n",
    "        'Vadodara': {'lat': 22.3072, 'lon': 73.1812, 'zone': 'West'},\n",
    "        'Surat': {'lat': 21.1702, 'lon': 72.8311, 'zone': 'West'},\n",
    "        'Nashik': {'lat': 20.0000, 'lon': 73.7833, 'zone': 'West'},\n",
    "        'Aurangabad': {'lat': 19.8762, 'lon': 75.3433, 'zone': 'West'},\n",
    "        'Bhopal': {'lat': 23.2599, 'lon': 77.4126, 'zone': 'West'},\n",
    "        'Indore': {'lat': 22.7196, 'lon': 75.8577, 'zone': 'West'},\n",
    "        \n",
    "        # Eastern Cities\n",
    "        'Kolkata': {'lat': 22.5726, 'lon': 88.3639, 'zone': 'East'},\n",
    "        'Patna': {'lat': 25.5941, 'lon': 85.1376, 'zone': 'East'},\n",
    "        'Bhubaneswar': {'lat': 20.2961, 'lon': 85.8245, 'zone': 'East'},\n",
    "        'Guwahati': {'lat': 26.1445, 'lon': 91.7362, 'zone': 'East'},\n",
    "        'Ranchi': {'lat': 23.3441, 'lon': 85.3096, 'zone': 'East'},\n",
    "        'Jamshedpur': {'lat': 22.8046, 'lon': 86.2029, 'zone': 'East'},\n",
    "        'Dhanbad': {'lat': 23.7957, 'lon': 86.4304, 'zone': 'East'},\n",
    "        'Bokaro': {'lat': 23.6693, 'lon': 86.1511, 'zone': 'East'},\n",
    "        'Cuttack': {'lat': 20.4625, 'lon': 85.8820, 'zone': 'East'},\n",
    "        'Asansol': {'lat': 23.6739, 'lon': 86.9524, 'zone': 'East'},\n",
    "        \n",
    "        # Central Cities\n",
    "        'Gwalior': {'lat': 26.2183, 'lon': 78.1828, 'zone': 'Central'},\n",
    "        'Jabalpur': {'lat': 23.1815, 'lon': 79.9864, 'zone': 'Central'},\n",
    "        'Raipur': {'lat': 21.2514, 'lon': 81.6296, 'zone': 'Central'},\n",
    "        'Bhilai': {'lat': 21.2092, 'lon': 81.4285, 'zone': 'Central'},\n",
    "        'Ujjain': {'lat': 23.1828, 'lon': 75.7772, 'zone': 'Central'},\n",
    "        'Sagar': {'lat': 23.8388, 'lon': 78.7378, 'zone': 'Central'},\n",
    "        'Durg': {'lat': 21.1900, 'lon': 81.3000, 'zone': 'Central'},\n",
    "        'Ratlam': {'lat': 23.3341, 'lon': 75.0376, 'zone': 'Central'},\n",
    "        'Satna': {'lat': 24.6000, 'lon': 80.8300, 'zone': 'Central'},\n",
    "        'Rewa': {'lat': 24.5333, 'lon': 81.3000, 'zone': 'Central'},\n",
    "        \n",
    "        # North-Eastern Cities\n",
    "        'Shillong': {'lat': 25.5788, 'lon': 91.8933, 'zone': 'North-East'},\n",
    "        'Agartala': {'lat': 23.8315, 'lon': 91.2868, 'zone': 'North-East'},\n",
    "        'Aizawl': {'lat': 23.7271, 'lon': 92.7176, 'zone': 'North-East'},\n",
    "        'Imphal': {'lat': 24.8170, 'lon': 93.9368, 'zone': 'North-East'},\n",
    "        'Kohima': {'lat': 25.6751, 'lon': 94.1086, 'zone': 'North-East'},\n",
    "        'Dibrugarh': {'lat': 27.4728, 'lon': 94.9120, 'zone': 'North-East'},\n",
    "        'Silchar': {'lat': 24.8333, 'lon': 92.7789, 'zone': 'North-East'},\n",
    "        'Tinsukia': {'lat': 27.4975, 'lon': 95.3533, 'zone': 'North-East'},\n",
    "        'Dimapur': {'lat': 25.9090, 'lon': 93.7276, 'zone': 'North-East'},\n",
    "        'Itanagar': {'lat': 27.1000, 'lon': 93.6200, 'zone': 'North-East'}\n",
    "    }\n",
    "    \n",
    "    try:\n",
    "        # Read original data to get the structure\n",
    "        original_df = pd.read_csv('data/pollution_data_comprehensive.csv')\n",
    "        print(f\"📊 Original data loaded: {original_df.shape[0]} records\")\n",
    "        \n",
    "        # Create enhanced dataset with virtual sensors for all cities\n",
    "        enhanced_data = []\n",
    "        \n",
    "        # Generate data for last 7 days for all cities\n",
    "        base_date = datetime.now() - timedelta(days=7)\n",
    "        hours_to_generate = 24 * 7  # 7 days of hourly data\n",
    "        \n",
    "        for city, info in INDIAN_CITIES.items():\n",
    "            # Create 2 virtual sensors per city\n",
    "            for sensor_num in range(1, 3):\n",
    "                sensor_name = f\"{city}_Sensor_{sensor_num}\"\n",
    "                \n",
    "                # Generate realistic pollution data based on city characteristics\n",
    "                if city == 'Delhi':\n",
    "                    pm25_range = (80, 300)  # High pollution\n",
    "                    pm10_range = (150, 500)\n",
    "                elif city in ['Mumbai', 'Kolkata', 'Chennai']:\n",
    "                    pm25_range = (50, 200)  # Medium-high pollution\n",
    "                    pm10_range = (100, 350)\n",
    "                elif city in ['Bangalore', 'Hyderabad', 'Pune']:\n",
    "                    pm25_range = (30, 150)  # Medium pollution\n",
    "                    pm10_range = (70, 250)\n",
    "                else:\n",
    "                    pm25_range = (20, 100)  # Lower pollution\n",
    "                    pm10_range = (50, 200)\n",
    "                \n",
    "                # Generate hourly data for 7 days\n",
    "                for hour in range(hours_to_generate):\n",
    "                    timestamp = base_date + timedelta(hours=hour)\n",
    "                    \n",
    "                    # Add some time-based variation (higher during day, lower at night)\n",
    "                    hour_of_day = timestamp.hour\n",
    "                    if 8 <= hour_of_day <= 20:  # Daytime - higher pollution\n",
    "                        pm25 = np.random.uniform(pm25_range[0] * 1.2, pm25_range[1] * 1.1)\n",
    "                        pm10 = np.random.uniform(pm10_range[0] * 1.2, pm10_range[1] * 1.1)\n",
    "                    else:  # Nighttime - lower pollution\n",
    "                        pm25 = np.random.uniform(pm25_range[0] * 0.8, pm25_range[1] * 0.7)\n",
    "                        pm10 = np.random.uniform(pm10_range[0] * 0.8, pm10_range[1] * 0.7)\n",
    "                    \n",
    "                    enhanced_data.append({\n",
    "                        'timestamp': timestamp,\n",
    "                        'sensor_name': sensor_name,\n",
    "                        'city': city,\n",
    "                        'zone': info['zone'],\n",
    "                        'sensor_latitude': info['lat'] + np.random.uniform(-0.02, 0.02),\n",
    "                        'sensor_longitude': info['lon'] + np.random.uniform(-0.02, 0.02),\n",
    "                        'PM2.5': pm25,\n",
    "                        'PM10': pm10,\n",
    "                        'NO2': np.random.uniform(10, 80),\n",
    "                        'SO2': np.random.uniform(2, 40),\n",
    "                        'CO': np.random.uniform(0.5, 3),\n",
    "                        'O3': np.random.uniform(10, 60),\n",
    "                        'temperature_c': np.random.uniform(15, 40),\n",
    "                        'humidity': np.random.uniform(30, 90),\n",
    "                        'wind_speed': np.random.uniform(0, 20),\n",
    "                        'area_type': np.random.choice(['Industrial', 'Residential', 'Commercial', 'Traffic'])\n",
    "                    })\n",
    "        \n",
    "        # Create enhanced dataframe\n",
    "        enhanced_df = pd.DataFrame(enhanced_data)\n",
    "        \n",
    "        # Combine with original data (if you want to keep original sensors)\n",
    "        final_df = pd.concat([original_df, enhanced_df], ignore_index=True)\n",
    "        \n",
    "        # Save enhanced data\n",
    "        output_file = 'data/pollution_data_all_india_enhanced.csv'\n",
    "        final_df.to_csv(output_file, index=False)\n",
    "        \n",
    "        print(f\"✅ Enhanced All India data saved: {output_file}\")\n",
    "        print(f\"🏙️ Total cities covered: {final_df['city'].nunique()}\")\n",
    "        print(f\"🗺️ Total zones covered: {final_df['zone'].nunique()}\")\n",
    "        print(f\"📡 Total sensors: {final_df['sensor_name'].nunique()}\")\n",
    "        print(f\"📊 Total records: {len(final_df):,}\")\n",
    "        \n",
    "        # Show distribution\n",
    "        print(f\"\\n📈 City Distribution:\")\n",
    "        city_counts = final_df['city'].value_counts()\n",
    "        for city, count in city_counts.head(15).items():\n",
    "            print(f\"  {city}: {count} records\")\n",
    "        \n",
    "        print(f\"\\n🌍 Zone Distribution:\")\n",
    "        zone_counts = final_df['zone'].value_counts()\n",
    "        for zone, count in zone_counts.items():\n",
    "            print(f\"  {zone}: {count} records\")\n",
    "            \n",
    "        return final_df\n",
    "        \n",
    "    except Exception as e:\n",
    "        print(f\"❌ Error: {e}\")\n",
    "        return None\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"🚀 CREATING COMPREHENSIVE ALL INDIA DATASET...\")\n",
    "    print(\"=\" * 65)\n",
    "    \n",
    "    result_df = create_comprehensive_all_india_data()\n",
    "    \n",
    "    if result_df is not None:\n",
    "        print(\"\\n🎉 SUCCESS! Enhanced dataset created:\")\n",
    "        print(f\"   ✅ {result_df['city'].nunique()} Indian cities\")\n",
    "        print(f\"   ✅ {result_df['zone'].nunique()} geographical zones\") \n",
    "        print(f\"   ✅ {result_df['sensor_name'].nunique()} total sensors\")\n",
    "        print(f\"   ✅ {len(result_df):,} total records\")\n",
    "        print(f\"   ✅ Realistic pollution patterns for each city\")\n",
    "        print(f\"\\n📁 Output file: data/pollution_data_all_india_enhanced.csv\")\n",
    "    else:\n",
    "        print(\"\\n❌ Failed to create enhanced dataset\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "53ae94b9-19af-4fbc-9133-a6f2d8d90000",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
